window_height: 1000
window_width: 1200
frame_rate: 119.88
treadmill_speed: 15.25
rolling_window: 15
change_threshold: 0
pixels_per_cm: 60.939
stance_threshold: 547
treadmill_y: 547
lowpass_filter_cutoff: 6